CREATE TABLE "GCG_3978_PART_SERIAL"(
 "REC_ID" INTEGER NOT NULL ,
 "PART" CHAR(20) NOT NULL ,
 "SERIAL" CHAR(5),
 "JOB" CHAR(6),
 "JOB_SUFFIX" CHAR(3),
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "SHIPPED" BIT DEFAULT '0' NOT NULL ,
 "RETURNED" BIT DEFAULT '0' NOT NULL ,
 "SUB_ASSEMBLY" BIT DEFAULT '0' NOT NULL ,
 "FG_SERIAL" CHAR(5),
 "FG_PART" CHAR(20),
 PRIMARY KEY ("REC_ID"));
